

service: checkpycompatible

frameworkVersion: '2'

provider:
  name: aws
  runtime: python2.7
  deploymentBucket: 
      name: bucketpy


functions:
  hello:
    handler: handler.hello
  

plugins: 
  - serverless-deployment-bucket
